### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by fritz8** [xibalba10/plugin.video.xxx-o-dus#10]
Get fetal error on search all providers

**Comment by xibalba10** [comment]
What version of xxxodus and script.xxxodus.scrapers do you have?

**Comment by fritz8** [comment]
3.00.010

**Comment by xibalba10** [comment]
I will be releasing an update tonight so please force check for updated tomorrow to make sure its up to date and then test for me please.

**Comment by xibalba10** [comment]
Please force check the repo for updates to get 3.00.012 and recheck. Thank you.

**Comment by imurreflection** [comment]
Hi,  I was also experiencing the same issue 
earlier but with this update,  it is not happening.  I can see all results for a particular keyword using search all providers option.
