### ISSUE TITLE
Chaturbate

### ISSUE THREAD

**Issue by Biz387** [xibalba10/plugin.video.xxx-o-dus#12]
I appreciate the work you are doing, but the new version seems to have lost some unique features.  

I really miss the view by tag option.

Also some explanation how yo change options such as default view would be great.

**Comment by xibalba10** [comment]
I did not realize that I did not put that back in. I will look to get it put back in soon.

With things like features please make sure you read the addon information link on the main menu as It explains about features that are in the context menu. The addon settings (accessible from the main menu [My Settings]) contains all options for views, chaturbate and more. Any more questions please ask.

**Comment by Biz387** [comment]
Great thanks, I looked at the settings but don't understand how to set them as they are set with 0's tried to change to 1 ie like a binary yes or no but didn't work

**Comment by xibalba10** [comment]
Every skin in kodi has different views and view ids, you would need to find the id for the view you want in your skin and set that as the number.

**Comment by xibalba10** [comment]
Tags have now been added on 3.00.012 Any other issues please open a new issue. Thanks.
