### ISSUE TITLE
New issue

### ISSUE THREAD

**Issue by jomico777** [xibalba10/plugin.video.xxx-o-dus#13]
Having tried the latest version...I have the following issues....
When you make a search...it shows them as thumbnails and as soon as you try to scroll down it changes to list...so you select thumbnails scroll and back it jumps into list.
Secondly if you watch any thing and try to close back out to return to the previous page ...you get redirected back through the search process...which quite frankly is time consuming.
Otherwise I have found this addon extremely good in the past...hopefully these are just glitches that will get ironed out.thankyou.

**Comment by xibalba10** [comment]
Thanks for the post.

Please confirm the version of the addon you are using.
Which skin are you using?
Which version of Kodi are you using?

**Comment by NewbiefromNJ** [comment]
Just installed 3.00.012 on Krypton 17.3 running custom Skin (Xonfluence) on Windows 10 PC. I am not experiencing this issue. 

Searches work fine when I go to Search/Search All Providers/New Search/
The results are all thumbnails and I can scroll thru all results with no issues. 

However, I've done many searches and can't seem to play anything. When I click on a thumbnail, nothing happens.

**Comment by jomico777** [comment]
Install 3.00.012 xxx-o-dus on krypton 17.3 using xenon xxx version 7
Thanks

**Comment by imurreflection** [comment]
Hi,  I have checked the issue on Jarvis and Krypton both but did not face it.  I believe  there could be an issue with the Skin.  I m using Aeon Nox Silvo and it works fine.

**Comment by xibalba10** [comment]
Ok if theres any issues specif to skin etc please recreate the issue and upload a debug log for me to look further. Thanks
