### ISSUE TITLE
Site Addition Request. 

### ISSUE THREAD

**Issue by imurreflection** [xibalba10/plugin.video.xxx-o-dus#14]
Hello my friend,  good day.  Can you please look at the possibility of adding sexix.net please.  This site has extremely good content in mostly HD.  It was working fine on Ultimate Whitecream but now it shows all content in 480p even when the description says 1080p and also most of the links are down. This site also has good Jav content.  Also unlike most of the tubes present in xxx-o-dus shows short length clips,  this site shows complete full length content.  And as usual,  thanks for the great job!!!

**Comment by xibalba10** [comment]
Hello, thanks for the question.

The issue is I do not want to just be cloning stuff from other addons.

UWC is an amazing addon in itself and I do not want to take users away for the same content.

I will pass your issue onto the dev of UWC and see if he can sort that issue out for you.

Hope this helps.

**Comment by imurreflection** [comment]
Mate,  it's not about cloning.  It's alternative. UWC was indeed an amazing addon but now it's not being developed.  Their Twitter and Facebook pages are closed.  I tried contacting Mortael several times and left messages here and on Facebook but he did not even bother to reply.  Why should the users be deprived of good content just because it is not working on another content which used to be amazing.  Please check UWC yourself,  sexix.net is not being updated for over a month now.  Check the site on Web browser and you will find the difference.  There are already some sites available on your lovely addon present on UWC also. Kindly consider your decision again mate.
