### ISSUE TITLE
Chaturbate issues

### ISSUE THREAD

**Issue by eSkRo32** [xibalba10/plugin.video.xxx-o-dus#2]
Hi and thx for your work! 

I think chaturbate cams always play in highbandwith even tho ive set it to low bandwith because it used to be fluid before with earlier  version 2.

And also, when setting bandwith to 'always ask' 
Well it asks Nothing,,, cam just start to play.. And i believe it plays again in highbandwith... 

Also, when entering a cam, altho unchecked in settings, i see the chatroom title notification popup.. 

Thanks :)

**Comment by xibalba10** [comment]
Hi there, 

XXX-O-DUS has been rewritten from the top to bottom over the last month.

The 3.00.004 update last night finished all changes to the scrapers for tubes and the search facility.

The only thing left for me to now finish on is chaturbate. 

The facilities XXXODUS offered for chaturbate were quite vast so it will take me a few days to get it all back in and working.

I will post here to let you know when the update supporting everything chaturbate should be doing is released.

**Comment by eSkRo32** [comment]
Perfect! Take your time :) 
Xxx-o-dus is amazing :)

**Comment by xibalba10** [comment]
Hi,

3.00.005 pushed, should now have full chaturbate support. 

I will close this ticket. If you have any other issues please log an issue.

Thank you.
