### ISSUE TITLE
Nothing works

### ISSUE THREAD

**Issue by mortael** [xibalba10/plugin.video.xxx-o-dus#5]
Nothing works, it was way better when that Echo fella was developing it :)

**Comment by imurreflection** [comment]
If you are talking about Xxx-o-dus,  everything is working fine.. And it's far better than UW.  Moreover,  this person is so helpful that cannot be explained in words.  I never expected this kind of support from a gifted developer like him.  He is an asset to developing community.

**Comment by mortael** [comment]
ffs, take it easy.....he asked to post an issue to test something, so i had a little fun...some banter between mates. Relax!!

**Comment by TheAlpha12** [comment]
nothing works all we see is onions  better when whats his name was in chart pfft
