### ISSUE TITLE
xnxx and xvideos

### ISSUE THREAD

**Issue by ghostguy** [xibalba10/plugin.video.xxx-o-dus#8]
xnxx and Xvideos don't loa for me
the "working" just keeps going on xnxx and Xvideo runs the "working for a bit then restarts my raspberry pi

thanks!!

**Comment by xibalba10** [comment]
Can you please try accessing this url via a browser please and let me know what you see.

http://www.xnxx.com/tags/

**Comment by ghostguy** [comment]
the link goes rightto the site, and the page opens to the tags page and the vidoes can be accessed and they run fine

**Comment by ghostguy** [comment]
i've tried restarting kodi abd uninstalling, restarting and then installing, but that does fix it. What I've noticed is,on the "tubes" links that work, when Iclick the link it spawns a "working" message for a few seconds, then a "" youporn is updated" message, then the link opens and works, the links that don't work never get that "xnxx or youjizz or Xvideos is updated" message, the "working " just runs
